version: "3.1"

services:

  ###postgres
  postgre:
    image: postgres:latest
    environment:
      - POSTGRES_USER=myspringboot
      - POSTGRES_PASSWORD=myspringboot
      - POSTGRES_DB=my_springboot_db
    ports:
      - "5442:5432"

