spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/my_springboot_db?ApplicationName=myspringboot
    username: myspringboot
    password: myspringboot
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

app:
  jwt-token:
    signature-secret: "test-sp-sgn-secret-do-not-delete"
